### ISSUE TITLE
Tabs do not have underline on Firefox

### ISSUE THREAD

**Issue by taroj1205** [yamada-ui/yamada-ui#3555]
### Which package has an issue?

@yamada-ui/react

### Package Version

1.6.3

### Description

Tabs on Firefox does not have underline.

![image](https://github.com/user-attachments/assets/e4fe6ef8-46ca-4986-b025-b18c1db9c15c)

### Link to Reproduction

https://yamada-ui.com/components/disclosure/tabs

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

This is on Chrome.
![image](https://github.com/user-attachments/assets/0192c5b9-6b7e-4f22-996f-4ff752b5599a)

**Comment by taroj1205** [comment]
It seems like on Firefox, the style below is not being applied.

```css
.css-8aqtwx:horizontal, .css-8aqtwx[data-orientation=horizontal], .css-8aqtwx[aria-orientation=horizontal] {
    border-bottom-style: solid;
    border-bottom-width: 1px;
    margin-bottom: -1px;
}
```

![image](https://github.com/user-attachments/assets/72fabe14-e024-40fb-9294-aa562696d159)
